language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  - secure: hvHgU6zwYZvHSd42N7byYMzSGBAjmD/QhTZn49E/OCK7agVK++gBNuR3sRVgy87rk6TCzq5eZFThInQokKhcicvClRi56PpyxeZGXQ5Dx/RasImVufp9Gp+RmNzqM/DmNNCR6LUl95K64KXvyNQ48Q0svkhJ3kwTNlcscjpjXB3iZfRrOO1SO6tlsDBhk94HG2+QzejJDRlfnXtu2qVt56PpkiiF7IT75k5IQUDnu8jghdCKnZR8z2EhyqPUACw5+clAJT1V7KCXLj9RMzwu8H7GGjs97hezBD4n+O2iqsSdKQVuZky1OyGOSFUSWolrtaJy8/IRk6Xmi/JKuB9EVtbFJ2pFM2EmLevJSFZTHpc8wAeqSQkScewwLAaKNGNBdkjTfwMzEjsD86Nzb5FKzgo86fc2cqdRqDAtRX41lijorX/08i87jmv3FFtcM7sM5m5IwFubrj4RUTAwUbci1w6FQPvcK4ybeX6cYqQWVk5MZHJbtoZmydKOWxK4vOBPhWn2XlhT2xKjii2Eice5cxJY0YNgqyM18VxCSXbj7mRfMWK0v+yEn5Tk0a1EszpZYGv1iuaZ5FDDonkj/tgcdJXNTRtWZrKH3+c0EDU098MLufCiTOVMliHNFQ93XFpX3sF7npBC29LQJ8Jzp1v8M8PuYXWKShoYBaeEvQc8Z20=
  - secure: PSxXqwBs/Wi/TkErk59msdRnzt2y+giLXUFpxR/OnwZoY62ZZCZnCRqx6IoTD6ePwCDbtxDuAUVVtEY/OM/x/ZgItr3dYhOor6IZLvF6r73rwwlvLZiwWKQiQhsYmo1R6aJeF75UNHkTuuND0R/vD1yo910CoJ44IeOfaXgbVWI0klGLbDgjdHcnPNM9iUDn2omNdpRKfaQWh+yfW/KMkddt1OZqoWxr1/KSpYVxYUmyR7A/V7ZVnYgESi2+6SZbsZpUFoaT0+kC6vhkIIsXxx/RlXFN0PCs4VdaQyIGYvHGUZsP2rnyYaWjUErAvrPhTU3dPlhmWDD8siM8RcKWl78nIY5sowETjB9lX6Cp9pQDD8cFNFF6xLS2tuxYxZrAFjHb4D/47BWTWFEe49AX1V/BKYGvRW5iWEBgwr6aE8q5ARng9RuHx+c2SVPtCxjryTAIX/EK2R/2SlnQ1qLm026UG3JeFnsx7EUq8souvIetMF02W2YLTWy0YrYCjdi+hu8pj+qQOY2vzCfMJXVvHOecS2yBgMQnq5KtDsidUk32AaUsH6djKgYk0BryTeXwzY98oM4dizmts4YxFR/3GjDEwMQ1UvUWbdDZOwCMafI07EavT6+1Xqh5D4NJAhx+2Hig+uWUi0/D+17yKDI8Pz8zB8wUtePcTPgzbBbbd7w=
  - secure: IdVKRh0ruYZa6OIOB+YaPp3pOs2TWDadPdQi6h+iFZ3yrLZ63D32lc3qaY/AkgB+VN8R9C4GvnG5iwkIa6tEctSTdWpth88828YwCh2QYx7LN3vUm3OvXCm7oA4H1O1EksGB8HNLxAJUqp0PJdNHIjtcTXohzJEGl6j16w7jaNqDGi9tQ/Sjl/P3eJtMFAqqUSz1LkCNYEjHHYMUNI67XT04tSk0iPCO3yGAq8Yx9N5xD/F3lFfVHV1c32XYHuyrnteRPYQ/pqAYiHoeP2qfGqBhPmy8MbUSoDq664XVd/A4pNT0+g6/wgWhZwVvFubIGbI1Hmb3GUKiOvR/FH4iV4AFl6uX+iRUq8OraAE7WpyjJTljM+g0/p4aPaJbrVUuhk5ZhOzfyXicQFm/19RZEuRtTzy7lvUaBgSBvLtGFJQ1TGQbp5gP7r1clvahJF4ebEKlzblr/gg8BQDa+YoqiRsX1TMFIREld6gPubCHMVpXlY1ancMZvJ6BkFlbXz0hGB2fU4btbDKJun1+Wp4gp57m3ZlTVTrVUsDb06J6xkX/ch+MplJhCuBXKM6HKknEUAH7ew6Fg3oTkE1ss3+V0/OTdHRTkD0GI4WM2zRF8pn8p0XSJwXvrzEs3tw/Mw5f2Ae903TCAg8jNkNe4geo4qNjUw1FGCJq9EtGpdbd7ZQ=
install:
- pip install -U platformio
- platformio platform install espressif8266@2.6.2
- platformio lib install ArduinoJson
- platformio lib install https://github.com/tfry-git/EmbAJAX#master
script:
- platformio run -e csg-esp8266-rota-travis
- platformio run -t buildfs -e csg-esp8266-rota-travis
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: mz3mvlIOR0kjYIeqRDCCC/JgG9tfJHEs06YrkE/3O7OftcsF777atkiLAesTRb3s+NuGHV29Q115jkzrj+kqgeyUvYs/wOsEZAW0Aq2B8I1mr9nFkccpA5r9DofG0PUbtxGoLFxYmizHBPguQD2lKgZpEIFVbOS81gOlzraJLbmv3hXtvlJhPHShaKYfx4Y+jN4RD6rgU1T301T/kQltBDd5zyCImte0dLp1NXn+No0fcFmvjawDEJt/JZf0yQCU94u8WPTUEwml5t5B46lPtvE+YBz73/WeCT6f+ubnicBlcv73CYtlg5QQjmZCdjJMCDKb2ZQy9cEaq9KA2qERg0ShUxVBQM9G9c0rdvUy0M5QbkUWZHmJU+hX9890ZDDvxL4pkyvlRcpVQ8DFyIuZuAsFFmhlPFaKwES1oy512wDb/J/0CsErogPmdQZDGKn8xn2p8UF6c3HZx5c5y5BDPNaTAa/8Dtd8AhlAamy+R6fj4YD+dQBB9gtoGLM6XUWiew9wCQ2P7w1FtcM7TerQ4KmL9QoCRGjtKopC/tHuPUJ2BhyXTEeRqQ9EckNvQGmUNDe9DjdJXS4xcHlA7Sf1e4NfLUqy2KfwsLya73ezjMruKqIEBbWWEqCq5Ru7SaFec5MWKtwiMLs8lJ+F8gr88WbPFhwqETKWLkoSWQ9utxI=
  file_glob: true
  file:
  - ".pio/build/csg-esp8266-rota-travis/*.bin"
  - ".pio/build/csg-esp8266-rota-travis/*.bin.gz"
after_success:
- set -e
- sudo apt-get install -y lftp
- lftp -c "
    set ftps:initial-prot '';
    set ftp:ssl-force true;
    set ftp:ssl-protect-data true;
    set ssl:verify-certificate false;
    open ftp://$FTP_USER:$FTP_PASS@ftp.iot.greggs.org:21;
    mirror -eRvvv $TRAVIS_BUILD_DIR/hosted tools;
    quit;"
