language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
    secure: jc7oZL+bZpmWrFgSFSHmLXiKowm5emgRy3LX0ZFl9ketLYjT+hRNDxAR8akjJZHyrR+Y1ROuytVaUFS4ASs+Cu28MEhO+DiUtZBmZIv5gTD19iXqdY7Ykaun0U3orGjROWNOHGFVJQS+w631Gd2Vnfs4mr70s9bUW/Edn1JtMTLIhkH8QiDtrKDbcwM2bk2cUMrAw0H6nYZ4begztFcy8bqxICmOEVxQOl4QP1SSUk8E3JAPVves8b8PLXW9i6Ng5Gdv7NQzLXCVeNMWJGYlLsx6VQ2x1jTGUJv/dfiMKD7H/HY/hzl0f5810k/EUUNnKBKrzIOcdlZLKynLRfFxgDt6BZdl+6Da1JfjEI3F/Wn4WT8hYCSUDxgIT9IY8kSLFiVDnsy+3KaQeaOONICYSifOtY/Vy/dMXcKl5zSShSQGA4mauAS0BrvQxk9HskXkU+0KnK6/E5z+Ut2Q3Zv5D7Z6cXodCNK5/JRwNf5msesmvIyszEHRAGdVLYXbOuILeJ5aWWcV/pxqHr22ilyL629HX7jobpvlGcwWONgGPBMfrE4awDQ05JO8aLXt/tOnF5Xkfs4Gao/r9B+nfWeAczmxcJhIP+d7pIGnsYX0Oz2W9oDHhOnDK31iBg4VcbZPTGzD95c0Wc+L5B0BoJ1Fgc5GLYg1w4CS05OmpJZ5UM8=
install:
- pip install -U platformio
- platformio lib install WiFiManager
- platformio lib install ArduinoJson
script:
- platformio run -e csg-esp8266-rota-ota
- platformio run -t buildfs -e csg-esp8266-rota-ota
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: Xx5JIGkkOUYyNXXYlVk5kLTwTUZGH4dEZLU4fL4f2Q6mtQZ27YjyVE7N+vYtyHzbkOf+zvfPQrZqHMG6R1XCeuEfZ4EDWOdWHfaViB08SdeHum5o2Etyak38llY8Cp4NZzKxiNokXyuVr4Gq6krD1FLVF5kBpi0iCsZ4LKiN4ddXJH5+X7W1R4w+0N5yCIDyLvTy4grZuYmwtxj4JQHWzgQKzthauB0Gq73YUHBPk62iVRlsM/IWYHgUxPXmIZLVRnEPQCcx8oJuRrTlZUNLGCfpXCq9MJGaMwJqMRo/3eeFdYSS91eCSN5TGWAGjea8EMfZu2WAvGvE4ToJJgPpyurh1U64CauUP9Wca3mp/HudfHd7WZ+y3LAKsUVwNMYUX+4QDdmFpIkNrAKRqFf4TrdRaFiCyq8aTwJwFa6ZkZp2bTXn8RMptRAHgx+5W+sRWyAiRhbPX0TO/j+5c+1obLzucwDF3JkAg5cH2unxAn+5Gx364PycBccmliXWOPtCM7LhtLvG6g/niyJszvNf5IzzquoYovRnW0+3Dfj5Ffh5+r8AjSWV9meBa+990qrFr6HcunrJEbJVjvxe/tKKFAEjCJMDRtAd43SKcAgujDllSZgYigbubqL9caAHCu76fax0OVdlITiz5z5oyMzy1MVmkPIEpt25cD+PEoPA+iY=
  file_glob: true
  file: ".pio/build/csg-esp8266-rota-ota/*.bin"
