language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  - secure: QEMjcsqEQhW8E/BKIt1AuFs4C63jsNHm2Dr0gpJuZBT8EQYy695rbgg2p8K1Hl1KrUEtRc2arvvcO3D9xIlZ7J4az3iR3u+zbq2dEw+6estX9C8LMm0LpdnQiFCgKnC6Ob6Wai0ypf3wJhWkFeeEc+th+eS6jbPIqUkrCMXhaM80YxcrUd1W340DrXIXCCFAgPxIVrWLdhc0uykP9+esNrCbzIf9QG6khZQHLfF7oOIiWccp/rjyYQizQGzEmYJjRoRhTEVqQ82WD05huZm/aSzOCYVXQgUFCV66b5a3AB8qLUJxj1VttxMgtJI13Ko0wUrLL47+HJ4SgrVZqQ3hOyd5nwZ2zrGeAFFDD14dE+2JME82WUAgpYHeO3vGyOwAiiNZUMkWZCerBnwb9OzN4DDuDW1tcFlIwOq+XhWO45p5hQdNyt5OEFi+umlcITURtgtpcP9rwxbVGBDv8nVzkM3sHEnawtVgIVAHDPnGl76ovfWVhWxSDVkYY+FdKusYQnSoGZvLkLWCdw5r0hKvEfCARJlMUVSmkFTV6ogNLgsTh6WZlSkeGktFXWBitMC5Bhf78+oGoz3IaCWU70iVhsK8lftP9HmDrQA7uGPzvqW81diP/Tk6KBjfgVUEaRcSpSNl5lEHRtmSgqtLQL1/JvTRMftbg10HyVdhv5Esh1Y=
  - secure: aY1GivvuJHEbyq79D4OWf/SRnmsYMbOl0sEC+NeUUFkYqRLmgQI0wxrpUW8i3YYOkGal+9wFennn3vhAe6xY7Nfk8xFuweHGeEc/0vvNftYqBDs33krl3a7bHXTSVyERp7baGSyOiQmmEDwyx+n7aDSgjlZdyexGxzP7WnDUmqQTJUGBN11tJ8YuIGgS6+vSiZiNCVZcVgqgIrY5096hoNbb4TzPN5tpboM0PRa6cUgUjhEwy1H+R4xWjEfyHM/ToHhzb+aBXWTxSFTo2nHRzjsmbI52If6nB+haBykW8R2583pTk5S3regi9jEbAE4QeCN/weq4fsZx4yBLe+LiI2Mk3ZKLo4l6fDBRij5f0FIOtnjagsrTkSTpeY9Cnxty2+vrge59Q7uV/mpG84zWq6y3o/XNbkTsCqbkNXLVOw8pcBqGw7l5LQwS5VPp+jc6cwZWaOtsv6ucLYmIDH5hDrRghZChuj66OlPkWx5QrIoXdkp9Tdy7G8OUEhO3NpBExExQVTM7aLaXoc2Yw4uRgRe6GNt7F+KFDThUHYNf456eTJSDV9qXlKLaDg1jWwQTgFmnZcDKsIKYLMn3PmEIVa6hZGnhffP3W2Qy6YR5jqe+y6c0q8UZeKyqDy/uT5p7CR/lLHhQkTnotnlOGYdm0lnxryKOTB8zkG9VDC8r+6I=
install:
- pip install -U platformio
- platformio lib install WiFiManager
- platformio lib install ArduinoJson
script:
- platformio run -e csg-esp8266-rota-travis
- platformio run -t buildfs -e csg-esp8266-rota-travis
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: TpxjT3CKVLiplHaZLzRyNaFi9IfG4tI+b5zhQvUA4xnzoJWYCtKr8DVe22yNdEcze8Z2KO9KkC4UCcTTt6ZVQLMZSst/SA2/yiwbvKbHSP6Ise27tTgg1j3G9Tzb4R2oDyv7DHutd2lRJfxUzhPsS1ZvUvPyjyiZjqy4/vygMjr0BBbP8rysfGzCvUy+LF09cFhYCT0Q1+Ua+me8WnwO5asoAeR0fhMDxNw4LLmJj/V5EQ4pTLGSyuNbQl/8IIQ6CECzyP0CeYUaIwEierPdgen1HlzOzmcfU7BBt82dB4DTndJryERa0gGYL2OSvNa9fr0rYtMoOT5bQBYXipoenGkNdlJQnVL7Lzy/Veqqi9Jy4es8WPqy7bFZZQ2W2w52eorr0fL38+2KGahkr7U3PMGaS2D4/HgYEgruJwkIMHz2pOau8uWZyq8+76Wfb14mhLaYzetie+/B7/feFdgQDOFNWU/SduIWlOTDCnMc5vAwCAI7u7BHU7e/SNicxQGptw9d8gOLWuEAysxzQbjd+DdYEZj08GVIeHCd6WqM24SCBGey58ehM3Xnhi1T1wWexYB8KaWQG0hBJv76cPwib3LmF1YXlesRCCI6N0fMBMIsgNEBZbfS7KsrSDAK/x5zgpN9WJjLn1Kr/wi+68b/Ol5hHISOH4VIPunKEbM4SLk=
  file_glob: true
  file: ".pio/build/csg-esp8266-rota-travis/*.bin"
