language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  - secure: hvHgU6zwYZvHSd42N7byYMzSGBAjmD/QhTZn49E/OCK7agVK++gBNuR3sRVgy87rk6TCzq5eZFThInQokKhcicvClRi56PpyxeZGXQ5Dx/RasImVufp9Gp+RmNzqM/DmNNCR6LUl95K64KXvyNQ48Q0svkhJ3kwTNlcscjpjXB3iZfRrOO1SO6tlsDBhk94HG2+QzejJDRlfnXtu2qVt56PpkiiF7IT75k5IQUDnu8jghdCKnZR8z2EhyqPUACw5+clAJT1V7KCXLj9RMzwu8H7GGjs97hezBD4n+O2iqsSdKQVuZky1OyGOSFUSWolrtaJy8/IRk6Xmi/JKuB9EVtbFJ2pFM2EmLevJSFZTHpc8wAeqSQkScewwLAaKNGNBdkjTfwMzEjsD86Nzb5FKzgo86fc2cqdRqDAtRX41lijorX/08i87jmv3FFtcM7sM5m5IwFubrj4RUTAwUbci1w6FQPvcK4ybeX6cYqQWVk5MZHJbtoZmydKOWxK4vOBPhWn2XlhT2xKjii2Eice5cxJY0YNgqyM18VxCSXbj7mRfMWK0v+yEn5Tk0a1EszpZYGv1iuaZ5FDDonkj/tgcdJXNTRtWZrKH3+c0EDU098MLufCiTOVMliHNFQ93XFpX3sF7npBC29LQJ8Jzp1v8M8PuYXWKShoYBaeEvQc8Z20=
  - secure: eH/05bke8IHGNSSRK/H9ioAXIhIhf3o2Guk7V0mU7rBTeftS/nzPVMG9Kg7L+Qz+i1Z6aXG4LHeMn8KCX8rLZ/2Xw5x5Enq18cW0X9kysLmXE2k/rm0WBnJpxr5DJIvHyYOHxqbi86GzuGQ7196ps8CXQzD0kbxoKnNFowXREMrMUWfjY4SwaMgFYyTUIsn7OtRhcO9slzUwl/26hMbYgn4uGTwoNiwOYrn35IxlJnByamQKUTSAo/LVLBaa5vDCfjgNOR5K+7j92aPdmpXuwsQELWLfT8nzYRpSd3bK5NMQidyYmmWu6DeJ3WhNIAtdwqq0l5fD6T/H/5Io3S3hXC4s9Cg27a6WVr+5UoaJ9YHate1vxvGfj2lmaMwk7m7GPZMJRIRxug/bBcaa8ijauSTasPNTd/iubNgff98djhbooELX95mX178oC2hoZNeIigVv6zi/Y+XMMIyLwmDu56f3KceerDEIPR/S7Hzeqg8ul67OUj2fwqSOceeH+gHxBpunp9yRmgr8d23vxkzhKiLhd8+eggmxzIa/tQATbGp8itMryLUxH5pjUXURXyPnpE2zHJUUs59kN1qmimQXf0P7fbKXNOnOABae7MXjfYTYmO4OZAwmniphJ0SRFX3e1pUeYYsHvQQTkIDWt6Xbq9GhPg1azTTiRxfEQqleNWY=
install:
- pip install -U platformio
- platformio platform install espressif8266@2.6.2
- platformio lib install ArduinoJson
- platformio lib install https://github.com/tfry-git/EmbAJAX#master
script:
- platformio run -t buildfs -e csg-esp8266-rota-travis
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/hosted/iot.greggs.org/ $SSH_USER@iot.greggs.org:public_html
    - chmod 600 /public_html/tools/*
  on:
    branch: master
addons:
  ssh_known_hosts: iot.greggs.org
before_deploy:
- openssl aes-256-cbc -K $encrypted_c79cb383f093_key -iv $encrypted_c79cb383f093_iv
  -in travis-godaddy_rsa.enc -out travis-godaddy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis-godaddy_rsa
- ssh-add travis-godaddy_rsa
