language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"

if: tag =~ /^\d+(?:\.\d+){2}$/

env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  # Logger - LOGGER__SERVICE_KEY
  - secure: hvHgU6zwYZvHSd42N7byYMzSGBAjmD/QhTZn49E/OCK7agVK++gBNuR3sRVgy87rk6TCzq5eZFThInQokKhcicvClRi56PpyxeZGXQ5Dx/RasImVufp9Gp+RmNzqM/DmNNCR6LUl95K64KXvyNQ48Q0svkhJ3kwTNlcscjpjXB3iZfRrOO1SO6tlsDBhk94HG2+QzejJDRlfnXtu2qVt56PpkiiF7IT75k5IQUDnu8jghdCKnZR8z2EhyqPUACw5+clAJT1V7KCXLj9RMzwu8H7GGjs97hezBD4n+O2iqsSdKQVuZky1OyGOSFUSWolrtaJy8/IRk6Xmi/JKuB9EVtbFJ2pFM2EmLevJSFZTHpc8wAeqSQkScewwLAaKNGNBdkjTfwMzEjsD86Nzb5FKzgo86fc2cqdRqDAtRX41lijorX/08i87jmv3FFtcM7sM5m5IwFubrj4RUTAwUbci1w6FQPvcK4ybeX6cYqQWVk5MZHJbtoZmydKOWxK4vOBPhWn2XlhT2xKjii2Eice5cxJY0YNgqyM18VxCSXbj7mRfMWK0v+yEn5Tk0a1EszpZYGv1iuaZ5FDDonkj/tgcdJXNTRtWZrKH3+c0EDU098MLufCiTOVMliHNFQ93XFpX3sF7npBC29LQJ8Jzp1v8M8PuYXWKShoYBaeEvQc8Z20=
  # IPInfo - Token
  - secure: hfXJGp5E7344Vog5OhK88vD0lzpnW2YvABNOHLc9AJ3w3yZ4m8w80VenxrxDsYQdmRu6KDSI01qJcoGafo2EswlOlgl3o2AUMDfLCdw2DZC2LkiN+qQOQv47vMMm1dTzxq/g6m/1YLCXAmQUv1/Q++xQGVoJaorZx127jk+wtEoBXMw3gcKZVhMRKbD8r/xCEWoHs3F6t8ShHziVXa2guQsRbyd6//ePG+4PprpWdMSd4ydhEcJGLyNM5M05UM5y54kDo+G2f5zFcBQ8bEyYGqMXOUdHcgYACY+HBc+OB0kbBtHCoaci1ayFZknRRAj2eD8Uo9UhFcDnrr0lhqEmIbgX+52HIXVvnE9L/qzeqKj28yNKR1NyQ9bHm5OEhIaxG5RSSLc/l+GQM8HtI0UEm7Tx5TyedrFBlTK4PKLZwsMknXebD5lzfBjpRSm8FvJen1nGbIeJRU1IaPTXPiiOWs8z7u7dVSPbJfeRqHiu3yPem25ZqUBDhrZz0Wi05Vt+sdVDQpTsyALGRFGUaL3vTfjSWH6dTVfxD99qkf74HuYc25Fh84FAvOB4+9pXcTMMb/7HgCJ3wVaP8kWda/nh1DgYUMdMJIlAdUzyyM7y8c8Guw2XZ/aTXQ8lAq1yYLv346wAWlCq5vHACtD3CzUPWXEM4y/b4RGKFj3KdC4EhaQ=

install:
- pip install -U platformio
- platformio platform install espressif8266@2.6.3
- platformio lib install ArduinoJson
- platformio lib install DoubleResetDetector
- platformio lib install ezTime
- platformio lib install https://github.com/tfry-git/EmbAJAX#master
- platformio lib install thinger-io/thinger.io

script:
- platformio run -t buildfs -e travis
- platformio run -e travis

# Deploy binaries
deploy:
  - provider: releases
    overwrite: true
    skip_cleanup: true
    on:
      repo: csgregg/csg-esp8266-rota
      all_branches: true
    api_key:
      secure: c19w5t9Nw8B58j9hYx7fKWQ4x79kQjSQffZwodePpqdp2yyS3nVW/z+NZPugSPX0FkahAGDdlSjdGlWgp6QQrtB4yV2w+k9mIjxwk6IF3LxY9z0wpnqiuGHDjEG0n887MhU3quQ9Dq/NqUCWn72aYPFZcNXCIwKELv5L5UI745zE7TnSoKLuGd1Hrhd5S6qOfCBxfMYsrHMMYCRH3sGthL07gUqBAYcwHX2nqqlRW9j9m+ebsdqghVoyQSZLElJzKLomc4VtgvmRrRs5hjjZO00RDARje/DnLxQa2NS6npgJhuaOtMd/tGzU0aruhccbUm75O2oKDnRtU5knwcCY1x1Y/x7jc4s88EL5jDQ34oTPYRH59v350GYkczvREPDQMICKrNySW6VcAj0JTvQDMpGrnXqxzgNz60YbVJbWT0gwFU9tyTVcDj8Nx5FdNKz9OAEI5yN4j7blcXm3u03pKeTCOqTz/Fv4saK54VBcJ4hwiObinNZ4NhvFhy6lmFjwIu7iRsSZO185YD6EhgsDvwKrsMonUC+R6TN1Hw0puBqiJyrebOoxy51SuWADwVeWgrsdOAEpFHcmvWCtN2pL+jOgqMK1dq5hEpGVnAyYe79Y69KiezTdu+/marXq1II8BB1sEyqhmSd+fjLdgrymVhOC3MRpx8h6dPU+1A71i88=
    file_glob: true
    file:
    # Upload assets to GitHub
      - ".pio/build/travis/*.bin"
      - ".pio/build/travis/*.bin.gz"



