language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  - secure: C2DFaV0ZKjjpw2hCcCC98dPiYQHWz2ZQ05n/SfHRchQ7YTjbvcWC1o8jzjmsinfoidvMIpUfOGT5ewHAl4zka4fEpYrHCAlUd2A8sX1kpGKP2QW8PKh3wV4kFJq8M8zgxhejesuKHGiIQZ/fQzsPO5TtWfYdGvOv1xKtuvod9R+CMxY3fGxx6My0zFT5AILW1rPcX6RB++0QO0xpLDmKRpqi4pn91u4bbrpDhmQPn4LQEWH0C2dt6qH4R79Bydcz/JjylR7P3dZJe7rAM4X1Wl4kr0BmLgo9wZ7Ac4Ov/wphDS5ReHMwICCSv7ppvmeffsyyHunRIPlQc5W/cU7nNSgipGq9BcfkD75LsrMLv8cd8sHXBEHFDWEadwyKNlV+y0GHWu0yBvAMQsZ8mkZj7jxy559yITb+dzUb6EFvXiGc2FEo38R5ooPRWzdhFlPQxpG7UmPPeOKl9q3sRjH1egYnQRgnQtW2anzhzsyWWSopWYtICrd+FlmJ9vlpoySuotFdLfw4+txReEsBG8idfvmjNh6cBVwlyC6KPcCT30PfW3Dn5dB0l0XIMgfdCwIcTfRBjBYiPK+7PtntH9A3/NMkK7018NZU2Kq/5eFTVqNA3QpQ5IyTu0tVgJB6FZgm+iVn5zkwICVwQv5Aoez723V5GKbUo487LwrPy+/vGAw=
  - secure: hegF1rs/I7ezPO59OU169FE6zqz9++aeiIqv42jQgsvcGVXGYZb/eLfdM70E4kMGspMehXoN7Y0vbq91fkKILiY1p9yuFKZQLLBIMr6Rzn8kmNe7JpESyJrgU4Mjv7KK/4aUGlEmrBMlzuCfqK4ZlJ99QqHDVhI1vmSk4gem3y/BeSJrfvTE/88GI07v+xfSMlP2EVOS3SDuuLUJ0sw4U8V/WBkdNaIwc4gJtSdDmYFCOH+Eitc5HEX6Y0VxLQQE7JJ5iqqVoS7Mr48T7ywJ4srKt+d7mHGShDBsGcuPJ7FrjeouQnfxr07jXcvjoeTdLa5StuREPHE4WT68LWXWz6W/hDGfbEuAUaPZFbkkClHpDS+WwmmGq3R1mJNAFL3wzggtwpau1W1vgWc7Z12dZr3AJkYTDhNE9ojHa5GJZp0EowkXOzWwCccpFNjA1IfFe47r9yK01V0zs804XnYUTwMlhHL4WHefNSpwufc8B3FMDjGjZ1CPIwQD2wghXVvvrfgcXA+QI1u+MHSvZtFPFd7b0PU4G1gLGp+lLmuotO4DAP3DANRLJmgXNNKKir129FOaNbGpNrBmsx2kd/KEOL2oyr/KnESD5ygFGTODaX2SyL7fRjfvLkqiF7TgUW++jySyGhmog2GnTfpYva6/LPZaz2bx+p7eRnOtcF3bdqs=
install:
- pip install -U platformio
- platformio lib install WiFiManager
- platformio lib install ArduinoJson
- platformio lib install Esp
script:
- platformio run -e csg-esp8266-rota-travis
- platformio run -t buildfs -e csg-esp8266-rota-travis
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: TpxjT3CKVLiplHaZLzRyNaFi9IfG4tI+b5zhQvUA4xnzoJWYCtKr8DVe22yNdEcze8Z2KO9KkC4UCcTTt6ZVQLMZSst/SA2/yiwbvKbHSP6Ise27tTgg1j3G9Tzb4R2oDyv7DHutd2lRJfxUzhPsS1ZvUvPyjyiZjqy4/vygMjr0BBbP8rysfGzCvUy+LF09cFhYCT0Q1+Ua+me8WnwO5asoAeR0fhMDxNw4LLmJj/V5EQ4pTLGSyuNbQl/8IIQ6CECzyP0CeYUaIwEierPdgen1HlzOzmcfU7BBt82dB4DTndJryERa0gGYL2OSvNa9fr0rYtMoOT5bQBYXipoenGkNdlJQnVL7Lzy/Veqqi9Jy4es8WPqy7bFZZQ2W2w52eorr0fL38+2KGahkr7U3PMGaS2D4/HgYEgruJwkIMHz2pOau8uWZyq8+76Wfb14mhLaYzetie+/B7/feFdgQDOFNWU/SduIWlOTDCnMc5vAwCAI7u7BHU7e/SNicxQGptw9d8gOLWuEAysxzQbjd+DdYEZj08GVIeHCd6WqM24SCBGey58ehM3Xnhi1T1wWexYB8KaWQG0hBJv76cPwib3LmF1YXlesRCCI6N0fMBMIsgNEBZbfS7KsrSDAK/x5zgpN9WJjLn1Kr/wi+68b/Ol5hHISOH4VIPunKEbM4SLk=
  file_glob: true
  file: ".pio/build/csg-esp8266-rota-ota/*.bin"
