language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
    secure: C2DFaV0ZKjjpw2hCcCC98dPiYQHWz2ZQ05n/SfHRchQ7YTjbvcWC1o8jzjmsinfoidvMIpUfOGT5ewHAl4zka4fEpYrHCAlUd2A8sX1kpGKP2QW8PKh3wV4kFJq8M8zgxhejesuKHGiIQZ/fQzsPO5TtWfYdGvOv1xKtuvod9R+CMxY3fGxx6My0zFT5AILW1rPcX6RB++0QO0xpLDmKRpqi4pn91u4bbrpDhmQPn4LQEWH0C2dt6qH4R79Bydcz/JjylR7P3dZJe7rAM4X1Wl4kr0BmLgo9wZ7Ac4Ov/wphDS5ReHMwICCSv7ppvmeffsyyHunRIPlQc5W/cU7nNSgipGq9BcfkD75LsrMLv8cd8sHXBEHFDWEadwyKNlV+y0GHWu0yBvAMQsZ8mkZj7jxy559yITb+dzUb6EFvXiGc2FEo38R5ooPRWzdhFlPQxpG7UmPPeOKl9q3sRjH1egYnQRgnQtW2anzhzsyWWSopWYtICrd+FlmJ9vlpoySuotFdLfw4+txReEsBG8idfvmjNh6cBVwlyC6KPcCT30PfW3Dn5dB0l0XIMgfdCwIcTfRBjBYiPK+7PtntH9A3/NMkK7018NZU2Kq/5eFTVqNA3QpQ5IyTu0tVgJB6FZgm+iVn5zkwICVwQv5Aoez723V5GKbUo487LwrPy+/vGAw=
install:
- pip install -U platformio
- platformio lib install WiFiManager
- platformio lib install ArduinoJson
script:
- platformio run -e csg-esp8266-rota-ota
- platformio run -t buildfs -e csg-esp8266-rota-ota
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: Xx5JIGkkOUYyNXXYlVk5kLTwTUZGH4dEZLU4fL4f2Q6mtQZ27YjyVE7N+vYtyHzbkOf+zvfPQrZqHMG6R1XCeuEfZ4EDWOdWHfaViB08SdeHum5o2Etyak38llY8Cp4NZzKxiNokXyuVr4Gq6krD1FLVF5kBpi0iCsZ4LKiN4ddXJH5+X7W1R4w+0N5yCIDyLvTy4grZuYmwtxj4JQHWzgQKzthauB0Gq73YUHBPk62iVRlsM/IWYHgUxPXmIZLVRnEPQCcx8oJuRrTlZUNLGCfpXCq9MJGaMwJqMRo/3eeFdYSS91eCSN5TGWAGjea8EMfZu2WAvGvE4ToJJgPpyurh1U64CauUP9Wca3mp/HudfHd7WZ+y3LAKsUVwNMYUX+4QDdmFpIkNrAKRqFf4TrdRaFiCyq8aTwJwFa6ZkZp2bTXn8RMptRAHgx+5W+sRWyAiRhbPX0TO/j+5c+1obLzucwDF3JkAg5cH2unxAn+5Gx364PycBccmliXWOPtCM7LhtLvG6g/niyJszvNf5IzzquoYovRnW0+3Dfj5Ffh5+r8AjSWV9meBa+990qrFr6HcunrJEbJVjvxe/tKKFAEjCJMDRtAd43SKcAgujDllSZgYigbubqL9caAHCu76fax0OVdlITiz5z5oyMzy1MVmkPIEpt25cD+PEoPA+iY=
  file_glob: true
  file: ".pio/build/csg-esp8266-rota-ota/*.bin"
