language: python
python:
- '3.8'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  matrix:
  - PLATFORMIO_CI_SRC=src/
  global:
  - secure: hvHgU6zwYZvHSd42N7byYMzSGBAjmD/QhTZn49E/OCK7agVK++gBNuR3sRVgy87rk6TCzq5eZFThInQokKhcicvClRi56PpyxeZGXQ5Dx/RasImVufp9Gp+RmNzqM/DmNNCR6LUl95K64KXvyNQ48Q0svkhJ3kwTNlcscjpjXB3iZfRrOO1SO6tlsDBhk94HG2+QzejJDRlfnXtu2qVt56PpkiiF7IT75k5IQUDnu8jghdCKnZR8z2EhyqPUACw5+clAJT1V7KCXLj9RMzwu8H7GGjs97hezBD4n+O2iqsSdKQVuZky1OyGOSFUSWolrtaJy8/IRk6Xmi/JKuB9EVtbFJ2pFM2EmLevJSFZTHpc8wAeqSQkScewwLAaKNGNBdkjTfwMzEjsD86Nzb5FKzgo86fc2cqdRqDAtRX41lijorX/08i87jmv3FFtcM7sM5m5IwFubrj4RUTAwUbci1w6FQPvcK4ybeX6cYqQWVk5MZHJbtoZmydKOWxK4vOBPhWn2XlhT2xKjii2Eice5cxJY0YNgqyM18VxCSXbj7mRfMWK0v+yEn5Tk0a1EszpZYGv1iuaZ5FDDonkj/tgcdJXNTRtWZrKH3+c0EDU098MLufCiTOVMliHNFQ93XFpX3sF7npBC29LQJ8Jzp1v8M8PuYXWKShoYBaeEvQc8Z20=
  - secure: ECpbsJPayYCZZG0gZFRjshr/yjm3PdlmKwo1K/bZNpoKvivl4ZOSrRbw8bEZPAvYzAGOhtFpOSxTKGode+invUKncX3oMfycsVYpO5A0KL3tw46ckHNP9N2lHillXgRSwY/eamLnlnk5IGW3l7YviTpcsa9SX95mX6X7h6MVykSdxrRd6WN1tWFG3DawOREAGpDB/cF6pSTSn59TcjMqYFZgByQfR7yQ2y9K0FXa9CDpLjTJb3Ou+ivQ1Cko+VomZf+qIkwlDsk1R4/lLCERQyNzcG9elJ9aSKfOiOlT29Oy6nsQf5EvGBcxxkZMgq0MC9qUAmQDhKw9+uuh+ytGnjYqRSq6+7gZHw42cEuoJIncG8OF4V0kW1gGfN3KZ59DIrzmdLTaAeeSFvGcmaBf4SX1467o2Hb1jdo62Ef5Z7o3QJJCevPnHdkao3Wtn7IK/BeAX2Yh/BUqJqW5IK5/6zruT1QyvwWovcAPlz22UTeEGyyFesaywOSlKRIYv3SSr+oRUaBmeuM8vr8m2Z1Ag8xyR7DPpPvjvTgJErs1QbAcMBO7tgzjvSA/+8xeOTviimn/xeFEjp7ROacWStfLbcRWcSBXlvveBGPL/AFioQ+9B5Hp1HNw48PvE88+PqW+BejyDuL2QfFpB7rH/sCg/E+zxB/qxzkbmhX6stMVNqM=
install:
- pip install -U platformio
- platformio lib install ArduinoJson
- platformio lib install https://github.com/tfry-git/EmbAJAX#master
script:
- platformio run -e csg-esp8266-rota-travis
- platformio run -t buildfs -e csg-esp8266-rota-travis
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  on:
    repo: csgregg/csg-esp8266-rota
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
  api_key:
    secure: mz3mvlIOR0kjYIeqRDCCC/JgG9tfJHEs06YrkE/3O7OftcsF777atkiLAesTRb3s+NuGHV29Q115jkzrj+kqgeyUvYs/wOsEZAW0Aq2B8I1mr9nFkccpA5r9DofG0PUbtxGoLFxYmizHBPguQD2lKgZpEIFVbOS81gOlzraJLbmv3hXtvlJhPHShaKYfx4Y+jN4RD6rgU1T301T/kQltBDd5zyCImte0dLp1NXn+No0fcFmvjawDEJt/JZf0yQCU94u8WPTUEwml5t5B46lPtvE+YBz73/WeCT6f+ubnicBlcv73CYtlg5QQjmZCdjJMCDKb2ZQy9cEaq9KA2qERg0ShUxVBQM9G9c0rdvUy0M5QbkUWZHmJU+hX9890ZDDvxL4pkyvlRcpVQ8DFyIuZuAsFFmhlPFaKwES1oy512wDb/J/0CsErogPmdQZDGKn8xn2p8UF6c3HZx5c5y5BDPNaTAa/8Dtd8AhlAamy+R6fj4YD+dQBB9gtoGLM6XUWiew9wCQ2P7w1FtcM7TerQ4KmL9QoCRGjtKopC/tHuPUJ2BhyXTEeRqQ9EckNvQGmUNDe9DjdJXS4xcHlA7Sf1e4NfLUqy2KfwsLya73ezjMruKqIEBbWWEqCq5Ru7SaFec5MWKtwiMLs8lJ+F8gr88WbPFhwqETKWLkoSWQ9utxI=
  file_glob: true
  file: ".pio/build/csg-esp8266-rota-travis/*.bin"
